const myPortfolio = [
  {
    id: 2,
    title: 'Conference Webpage',
    briefDes: 'It\'s an exact clone of Creative Commons summit webpage.',
    techList: ['JavaScript', 'html', 'CSS'],
    image: './images/data/image1.png',
    detailedDes: 'It is a clone of a creative commons seminar webpage and consists of two pages, both fully responsive for desktop and mobile phones.',
    liveLink: 'https://jasonfelice.github.io/First-Capstone/',
    source: 'https://github.com/jasonfelice/First-Capstone/',
  },
  {
    id: 3,
    title: 'Math Magicians',
    briefDes: 'Calculator App built with React.',
    techList: ['JavaScript', 'html', 'CSS', 'React'],
    image: './images/data/image2.png',
    detailedDes: 'Math magicians is a Single Page App (SPA) that allows users to make simple calculations.',
    liveLink: 'https://luxury-salmiakki-c12cfc.netlify.app/',
    source: 'https://github.com/jasonfelice/Math-Magicians/',
  },
  {
    id: 4,
    title: 'To-Do-list',
    briefDes: 'A simple to-do list web app.',
    techList: ['JavaScript', 'html', 'CSS'],
    image: './images/data/image3.png',
    detailedDes: 'It is a simple to-do list web app. Users can add tasks to the list and mark them as complete/incomplete. Built with JavaScript.',
    liveLink: 'https://jasonfelice.github.io/To-Do-list/',
    source: 'https://github.com/jasonfelice/To-Do-list/',
  },
  {
    id: 6,
    title: 'Bookstore',
    briefDes: 'Add books to a list',
    techList: ['html', 'CSS', 'React'],
    image: './images/data/bookstore.PNG',
    detailedDes: 'This website is built using React and Redux. Add or remove book from the list that is saved on the API.',
    liveLink: 'https://deft-babka-260201.netlify.app',
    source: 'https://github.com/jasonfelice/Bookstore',
  },
  {
    id: 7,
    title: 'SpaceX',
    briefDes: 'Book rockets, dragons, and join space missions',
    techList: ['html', 'CSS', 'React', 'Redux'],
    image: './images/data/space-x.png',
    detailedDes: 'The application fetches data from the SpaceX API and allows users to book rockets, dragons, and join selected space missions.​​',
    liveLink: 'https://brilliant-dolphin-a10874.netlify.app',
    source: 'https://github.com/d2ndjim/SpaceX',
  },
];

export default myPortfolio;