const myPortfolio = [
  {
    id: 1,
    title: 'Conference Webpage',
    briefDes: 'It\'s an exact clone of Creative Commons summit webpage.',
    techList: ['JavaScript', 'html', 'CSS'],
    image: './images/data/image1.png',
    detailedDes: 'It is a clone of a creative commons seminar webpage and consists of two pages, both fully responsive for desktop and mobile phones.',
    liveLink: 'https://jasonfelice.github.io/First-Capstone/',
    source: 'https://github.com/jasonfelice/First-Capstone/',
  },
  {
    id: 2,
    title: 'Math Magicians',
    briefDes: 'Calculator App built with React.',
    techList: ['JavaScript', 'html', 'CSS', 'React'],
    image: './images/data/image2.png',
    detailedDes: 'Math magicians is a Single Page App (SPA) that allows users to make simple calculations.',
    liveLink: 'https://luxury-salmiakki-c12cfc.netlify.app/',
    source: 'https://github.com/jasonfelice/Math-Magicians/',
  },
  {
    id: 3,
    title: 'To-Do-list',
    briefDes: 'A simple to-do list web app.',
    techList: ['JavaScript', 'html', 'CSS'],
    image: './images/data/image3.png',
    detailedDes: 'It is a simple to-do list web app. Users can add tasks to the list and mark them as complete/incomplete. Built with JavaScript.',
    liveLink: 'https://jasonfelice.github.io/To-Do-list/',
    source: 'https://github.com/jasonfelice/To-Do-list/',
  },
  {
    id: 4,
    title: 'Budget App',
    briefDes: 'Keeps track of your spendings.',
    techList: ['JavaScript', 'html', 'CSS', 'Rails'],
    image: './images/data/budget-app.png',
    detailedDes: 'This Rails Budget app allows users to record their transactions for a specific category.',
    liveLink: 'https://gentle-atoll-76081.herokuapp.com',
    source: 'https://github.com/jasonfelice/Budget-App',
  },
  {
    id: 5,
    title: 'Bookstore',
    briefDes: 'Add books to a list',
    techList: ['html', 'CSS', 'React'],
    image: './images/data/bookstore.png',
    detailedDes: 'This website is built using React and Redux. Add or remove book from the list that is saved on the API.',
    liveLink: 'https://deft-babka-260201.netlify.app',
    source: 'https://github.com/jasonfelice/Bookstore',
  },
];

export default myPortfolio;